### ISSUE TITLE
Issues with paint 

### ISSUE THREAD

**Issue by NaimBoufridi** [ScottyFillups/piko#1]
In my opinion the paint brush size should be regulated. The fact that you allow the size to reach over a 1000 is very disappointing...... I had more faith in you Phil, you've betrayed my trust, you've betrayed your potential.... MS Paint is superior to this bogus website, please reconsider your profession. No hard feelings buddy 👍

**Comment by philipjscott** [comment]
Nothing wrong with large pens Naim; are you jealous?

**Comment by NaimBoufridi** [comment]
No, I am not jealous of a dysfunctional, and disabled website....

**Comment by philipjscott** [comment]
:^)
